# Generated by Django 5.1.6 on 2025-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_en_ligne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
