# Generated by Django 5.1.6 on 2025-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_en_ligne', '0002_alter_produit_image_url_alter_produit_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='description_categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom_categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=100),
        ),
    ]
