# Generated by Django 5.1.6 on 2025-02-22 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_en_ligne', '0005_client_adresse_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='categorie',
            name='description_categorie',
            field=models.TextField(default='Description par défaut'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_produit',
            field=models.TextField(default='Description par défaut'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom_categorie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=255),
        ),
    ]
