# Generated by Django 5.1.6 on 2025-02-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_en_ligne', '0006_remove_produit_image_categorie_description_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='vente_en_ligne.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente_en_ligne.produit')),
            ],
        ),
    ]
