# Generated by Django 5.1.6 on 2025-02-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_en_ligne', '0007_commandeproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
